#!/usr/bin/env python

import os, django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "Collecster.settings")
django.setup()

from advideogame.models import *

company = Company.objects.create(name="Sega")
company.services.add(1)
company.services.add(2)
company.services.add(3)
company.services.add(4)
company = Company.objects.create(name="Nintendo")
company.services.add(1)
company.services.add(2)
company.services.add(3)
company.services.add(4)
company = Company.objects.create(name="Atari")
company.services.add(1)
company.services.add(2)
company.services.add(3)
company.services.add(4)
company = Company.objects.create(name="IBM")
company.services.add(1)
company.services.add(4)
company = Company.objects.create(name="Microsoft")
company.services.add(1)
company.services.add(2)
company.services.add(3)
company.services.add(4)
company = Company.objects.create(name="NEC")
company.services.add(1)
company.services.add(2)
company.services.add(3)
company.services.add(4)
company = Company.objects.create(name="SNK")
company.services.add(1)
company.services.add(2)
company.services.add(3)
company.services.add(4)
company = Company.objects.create(name="Sony")
company.services.add(1)
company.services.add(2)
company.services.add(3)
company.services.add(4)
company = Company.objects.create(name="id Software")
company.services.add(2)
company = Company.objects.create(name="Sonic Team")
company.services.add(2)
company = Company.objects.create(name="Sega-AM1")
company.services.add(2)
company = Company.objects.create(name="Sega-AM2")
company.services.add(2)
company = Company.objects.create(name="Sega-AM3")
company.services.add(2)
company = Company.objects.create(name="Sega-AM4")
company.services.add(2)
company = Company.objects.create(name="Sega-AM5")
company.services.add(2)
company = Company.objects.create(name="SCE London Studio")
company.services.add(2)
company = Company.objects.create(name="Sony Computer Entertainment Europe")
company.services.add(3)
company = Company.objects.create(name="Psygnosis")
company.services.add(2)
company = Company.objects.create(name="GT Interactive")
company.services.add(3)
company = Company.objects.create(name="Bandai")
company.services.add(1)
company.services.add(2)
company.services.add(3)
company = Company.objects.create(name="Realtime Associates")
company.services.add(2)
company = Company.objects.create(name="Altron")
company.services.add(2)
company = Company.objects.create(name="New Horizon studios")
company.services.add(2)
company = Company.objects.create(name="Virgin Interactive")
company.services.add(3)
company = Company.objects.create(name="Harmonix")
company.services.add(2)
company = Company.objects.create(name="MTV Games")
company.services.add(3)
company = Company.objects.create(name="Relentless Software")
company.services.add(2)
company = Company.objects.create(name="EMS")
company.services.add(1)
company = Company.objects.create(name="Team17")
company.services.add(2)
company = Company.objects.create(name="Ocean Software")
company.services.add(3)
company = Company.objects.create(name="Capcom")
company.services.add(2)
company.services.add(3)
company = Company.objects.create(name="Manic Media")
company.services.add(2)
company = Company.objects.create(name="3D Realms")
company.services.add(2)
company = Company.objects.create(name="Cave")
company.services.add(2)
company = Company.objects.create(name="Atlus")
company.services.add(3)
company = Company.objects.create(name="Smilebit")
company.services.add(2)
company = Company.objects.create(name="Wow Entertainment")
company.services.add(2)
company = Company.objects.create(name="Hitmaker")
company.services.add(2)
company = Company.objects.create(name="Overworks")
company.services.add(2)
company = Company.objects.create(name="EA Canada")
company.services.add(2)
company = Company.objects.create(name="Electronic Arts")
company.services.add(2)
company.services.add(3)
company.services.add(4)
company = Company.objects.create(name="InterAct")
company.services.add(1)
company = Company.objects.create(name="Westwood Studios")
company.services.add(2)
company = Company.objects.create(name="Aspect Co.")
company.services.add(2)
company = Company.objects.create(name="SIMS")
company.services.add(2)
company = Company.objects.create(name="Taito")
company.services.add(2)
company.services.add(3)
company = Company.objects.create(name="Mad Catz")
company.services.add(1)
company = Company.objects.create(name="2K")
company.services.add(2)
company.services.add(3)
company = Company.objects.create(name="Valve")
company.services.add(2)
company = Company.objects.create(name="Gearbox Software")
company.services.add(2)
company = Company.objects.create(name="Sierra Entertainment")
company.services.add(2)
company.services.add(3)
company = Company.objects.create(name="Namco")
company.services.add(2)
company.services.add(3)
company = Company.objects.create(name="Rage Software")
company.services.add(2)
company = Company.objects.create(name="Infogrames")
company.services.add(2)
company.services.add(3)
company.services.add(4)
company = Company.objects.create(name="Iron Lore Entertainment")
company.services.add(2)
company = Company.objects.create(name="THQ")
company.services.add(2)
company.services.add(3)
company = Company.objects.create(name="Blizzard")
company.services.add(2)
company.services.add(3)
company = Company.objects.create(name="Activision")
company.services.add(2)
company.services.add(3)
company = Company.objects.create(name="Stainless Games")
company.services.add(2)
company = Company.objects.create(name="SCI")
company.services.add(3)
company = Company.objects.create(name="Coktel Vision")
company.services.add(3)
company = Company.objects.create(name="LucasArts")
company.services.add(2)
company.services.add(3)
company = Company.objects.create(name="Lucasfilm Games")
company.services.add(2)
company.services.add(3)
company = Company.objects.create(name="Tose Software")
company.services.add(2)
company = Company.objects.create(name="Ubisoft")
company.services.add(2)
company.services.add(3)
company.services.add(4)
company = Company.objects.create(name="Pointsoft")
company.services.add(3)
company = Company.objects.create(name="Cyberlore Studios")
company.services.add(2)
