TAG_ID_LEFTPADDING_CHARS = 6 
TAG_MAX_LINES = 3 
TAG_MIN_COLS = 14 
TAG_FONT_TITLE = '/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf'
TAG_FONT_DETAIL = '/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf'
TAG_FONT_CHECKSIGN = '/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf'
TAG_SUPERSAMPLE_FACTOR = 8

SCALE_FACTOR = 4
TAG_INSTANCEDETAIL_HEIGHT = 25 * SCALE_FACTOR
TAG_INSTANCEDATA_SPACING = 5 * SCALE_FACTOR
TAG_QR_BOXSIZE = 3 * SCALE_FACTOR
TAG_FONT_TITLESIZE = 12 * SCALE_FACTOR
TAG_FONT_DETAILSIZE = 11 * SCALE_FACTOR
TAG_FONT_CHECKSIGNSIZE = 13 * SCALE_FACTOR
TAG_TEXT_BORDER_PAD = 2 * SCALE_FACTOR
TAG_CHECKBOX_SIDE = 10 * SCALE_FACTOR
TAG_CHECKSIGN_PAD = (1*SCALE_FACTOR, -2*SCALE_FACTOR)

PATH_MEDIA_INSTANCES = 'images/instances/'
PATH_TAGFILE = 'tag/tag.png'

URL_DM = 'dm/'
URL_ADD_INSTANCE = 'instance/add/'
URL_PRINT_INSTANCE = 'instance/print/'
URL_TAG_REDIRECT = 'admin/Datamanager/release/'

STR_WORK = 'Wk'
