TAG_IDPADDING = 5 
TAG_INSTANCEDETAIL_HEIGHT = 20
TAG_INSTANCEDATA_SPACING = 5
TAG_MAX_LINES = 2
TAG_MIN_COLS = 15 
TAG_QR_BOXSIZE = 2

PATH_MEDIA_INSTANCES = 'images/instances/'
PATH_TAGFILE = 'tag/tag.png'

URL_DM = 'dm/'
URL_ADD_INSTANCE = 'instance/add/'
URL_PRINT_INSTANCE = 'instance/print/'
URL_TAG_REDIRECT = 'admin/Datamanager/release/'

STR_WORK = 'Wk'
